services:
  frontend:
    image: registry.code.fbi.h-da.de/bpse-sose24/group-1/frontend:main
    ports:
      - 4242:4242
    env_file:
      - .env.production
    expose:
      - "4242"
  
  backend:
    image: registry.code.fbi.h-da.de/bpse-sose24/group-1/backend:main
    ports:
      - 4243:4243
    env_file:
      - .env.production
    expose:
      - "4243"
